package com.finishedbountynotify;

import java.util.HashMap;
import java.util.Map;

/** Quantities from https://oldschool.runescape.wiki/w/Bounty_tasks (wiki fallback). */
final class WikiBountyFallback
{
	private static final Map<Integer, Integer> QUANTITY_BY_TASK_ID = new HashMap<>();
	private static final Map<Integer, String> MONSTER_BY_TASK_ID = new HashMap<>();

	static
	{
		QUANTITY_BY_TASK_ID.put(438, 15);
		MONSTER_BY_TASK_ID.put(438, "Tern");
		QUANTITY_BY_TASK_ID.put(439, 15);
		MONSTER_BY_TASK_ID.put(439, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(440, 15);
		MONSTER_BY_TASK_ID.put(440, "Bull shark");
		QUANTITY_BY_TASK_ID.put(441, 25);
		MONSTER_BY_TASK_ID.put(441, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(442, 5);
		MONSTER_BY_TASK_ID.put(442, "Osprey");
		QUANTITY_BY_TASK_ID.put(443, 5);
		MONSTER_BY_TASK_ID.put(443, "Bull shark");
		QUANTITY_BY_TASK_ID.put(444, 5);
		MONSTER_BY_TASK_ID.put(444, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(445, 15);
		MONSTER_BY_TASK_ID.put(445, "Bull shark");
		QUANTITY_BY_TASK_ID.put(446, 15);
		MONSTER_BY_TASK_ID.put(446, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(447, 15);
		MONSTER_BY_TASK_ID.put(447, "Osprey");
		QUANTITY_BY_TASK_ID.put(448, 15);
		MONSTER_BY_TASK_ID.put(448, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(449, 5);
		MONSTER_BY_TASK_ID.put(449, "Tern");
		QUANTITY_BY_TASK_ID.put(450, 5);
		MONSTER_BY_TASK_ID.put(450, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(451, 5);
		MONSTER_BY_TASK_ID.put(451, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(452, 15);
		MONSTER_BY_TASK_ID.put(452, "Bull shark");
		QUANTITY_BY_TASK_ID.put(453, 15);
		MONSTER_BY_TASK_ID.put(453, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(454, 15);
		MONSTER_BY_TASK_ID.put(454, "Tern");
		QUANTITY_BY_TASK_ID.put(455, 15);
		MONSTER_BY_TASK_ID.put(455, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(456, 5);
		MONSTER_BY_TASK_ID.put(456, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(457, 5);
		MONSTER_BY_TASK_ID.put(457, "Bull shark");
		QUANTITY_BY_TASK_ID.put(458, 5);
		MONSTER_BY_TASK_ID.put(458, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(459, 15);
		MONSTER_BY_TASK_ID.put(459, "Tern");
		QUANTITY_BY_TASK_ID.put(460, 15);
		MONSTER_BY_TASK_ID.put(460, "Osprey");
		QUANTITY_BY_TASK_ID.put(461, 15);
		MONSTER_BY_TASK_ID.put(461, "Bull shark");
		QUANTITY_BY_TASK_ID.put(462, 30);
		MONSTER_BY_TASK_ID.put(462, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(463, 5);
		MONSTER_BY_TASK_ID.put(463, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(464, 5);
		MONSTER_BY_TASK_ID.put(464, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(465, 5);
		MONSTER_BY_TASK_ID.put(465, "Albatross");
		QUANTITY_BY_TASK_ID.put(466, 15);
		MONSTER_BY_TASK_ID.put(466, "Osprey");
		QUANTITY_BY_TASK_ID.put(467, 15);
		MONSTER_BY_TASK_ID.put(467, "Tern");
		QUANTITY_BY_TASK_ID.put(468, 15);
		MONSTER_BY_TASK_ID.put(468, "Bull shark");
		QUANTITY_BY_TASK_ID.put(469, 20);
		MONSTER_BY_TASK_ID.put(469, "Albatross");
		QUANTITY_BY_TASK_ID.put(470, 5);
		MONSTER_BY_TASK_ID.put(470, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(471, 5);
		MONSTER_BY_TASK_ID.put(471, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(472, 5);
		MONSTER_BY_TASK_ID.put(472, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(473, 15);
		MONSTER_BY_TASK_ID.put(473, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(474, 15);
		MONSTER_BY_TASK_ID.put(474, "Osprey");
		QUANTITY_BY_TASK_ID.put(475, 15);
		MONSTER_BY_TASK_ID.put(475, "Bull shark");
		QUANTITY_BY_TASK_ID.put(476, 30);
		MONSTER_BY_TASK_ID.put(476, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(477, 5);
		MONSTER_BY_TASK_ID.put(477, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(478, 5);
		MONSTER_BY_TASK_ID.put(478, "Stingray");
		QUANTITY_BY_TASK_ID.put(479, 5);
		MONSTER_BY_TASK_ID.put(479, "Spined kraken");
		QUANTITY_BY_TASK_ID.put(480, 15);
		MONSTER_BY_TASK_ID.put(480, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(481, 15);
		MONSTER_BY_TASK_ID.put(481, "Bull shark");
		QUANTITY_BY_TASK_ID.put(482, 15);
		MONSTER_BY_TASK_ID.put(482, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(483, 25);
		MONSTER_BY_TASK_ID.put(483, "Great white shark");
		QUANTITY_BY_TASK_ID.put(484, 5);
		MONSTER_BY_TASK_ID.put(484, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(485, 5);
		MONSTER_BY_TASK_ID.put(485, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(486, 5);
		MONSTER_BY_TASK_ID.put(486, "Albatross");
		QUANTITY_BY_TASK_ID.put(487, 15);
		MONSTER_BY_TASK_ID.put(487, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(488, 15);
		MONSTER_BY_TASK_ID.put(488, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(489, 15);
		MONSTER_BY_TASK_ID.put(489, "Mogre (sea)");
		QUANTITY_BY_TASK_ID.put(490, 25);
		MONSTER_BY_TASK_ID.put(490, "Stingray");
		QUANTITY_BY_TASK_ID.put(491, 5);
		MONSTER_BY_TASK_ID.put(491, "Osprey");
		QUANTITY_BY_TASK_ID.put(492, 5);
		MONSTER_BY_TASK_ID.put(492, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(493, 5);
		MONSTER_BY_TASK_ID.put(493, "Great white shark");
		QUANTITY_BY_TASK_ID.put(494, 15);
		MONSTER_BY_TASK_ID.put(494, "Bull shark");
		QUANTITY_BY_TASK_ID.put(495, 25);
		MONSTER_BY_TASK_ID.put(495, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(496, 20);
		MONSTER_BY_TASK_ID.put(496, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(497, 20);
		MONSTER_BY_TASK_ID.put(497, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(498, 5);
		MONSTER_BY_TASK_ID.put(498, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(499, 5);
		MONSTER_BY_TASK_ID.put(499, "Albatross");
		QUANTITY_BY_TASK_ID.put(500, 5);
		MONSTER_BY_TASK_ID.put(500, "Great white shark");
		QUANTITY_BY_TASK_ID.put(501, 20);
		MONSTER_BY_TASK_ID.put(501, "Stingray");
		QUANTITY_BY_TASK_ID.put(502, 25);
		MONSTER_BY_TASK_ID.put(502, "Osprey");
		QUANTITY_BY_TASK_ID.put(503, 15);
		MONSTER_BY_TASK_ID.put(503, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(504, 30);
		MONSTER_BY_TASK_ID.put(504, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(505, 5);
		MONSTER_BY_TASK_ID.put(505, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(506, 5);
		MONSTER_BY_TASK_ID.put(506, "Great white shark");
		QUANTITY_BY_TASK_ID.put(507, 5);
		MONSTER_BY_TASK_ID.put(507, "Manta ray (monster)");
		QUANTITY_BY_TASK_ID.put(508, 25);
		MONSTER_BY_TASK_ID.put(508, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(509, 25);
		MONSTER_BY_TASK_ID.put(509, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(510, 15);
		MONSTER_BY_TASK_ID.put(510, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(511, 25);
		MONSTER_BY_TASK_ID.put(511, "Great white shark");
		QUANTITY_BY_TASK_ID.put(512, 5);
		MONSTER_BY_TASK_ID.put(512, "Albatross");
		QUANTITY_BY_TASK_ID.put(513, 5);
		MONSTER_BY_TASK_ID.put(513, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(514, 5);
		MONSTER_BY_TASK_ID.put(514, "Stingray");
		QUANTITY_BY_TASK_ID.put(515, 20);
		MONSTER_BY_TASK_ID.put(515, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(516, 15);
		MONSTER_BY_TASK_ID.put(516, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(517, 25);
		MONSTER_BY_TASK_ID.put(517, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(518, 30);
		MONSTER_BY_TASK_ID.put(518, "Great white shark");
		QUANTITY_BY_TASK_ID.put(519, 5);
		MONSTER_BY_TASK_ID.put(519, "Stingray");
		QUANTITY_BY_TASK_ID.put(520, 5);
		MONSTER_BY_TASK_ID.put(520, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(521, 5);
		MONSTER_BY_TASK_ID.put(521, "Spined kraken");
		QUANTITY_BY_TASK_ID.put(522, 15);
		MONSTER_BY_TASK_ID.put(522, "Bull shark");
		QUANTITY_BY_TASK_ID.put(523, 15);
		MONSTER_BY_TASK_ID.put(523, "Osprey");
		QUANTITY_BY_TASK_ID.put(524, 15);
		MONSTER_BY_TASK_ID.put(524, "Tern");
		QUANTITY_BY_TASK_ID.put(525, 15);
		MONSTER_BY_TASK_ID.put(525, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(526, 5);
		MONSTER_BY_TASK_ID.put(526, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(527, 5);
		MONSTER_BY_TASK_ID.put(527, "Great white shark");
		QUANTITY_BY_TASK_ID.put(528, 5);
		MONSTER_BY_TASK_ID.put(528, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(529, 15);
		MONSTER_BY_TASK_ID.put(529, "Osprey");
		QUANTITY_BY_TASK_ID.put(530, 15);
		MONSTER_BY_TASK_ID.put(530, "Bull shark");
		QUANTITY_BY_TASK_ID.put(531, 15);
		MONSTER_BY_TASK_ID.put(531, "Tern");
		QUANTITY_BY_TASK_ID.put(532, 20);
		MONSTER_BY_TASK_ID.put(532, "Spined kraken");
		QUANTITY_BY_TASK_ID.put(533, 5);
		MONSTER_BY_TASK_ID.put(533, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(534, 5);
		MONSTER_BY_TASK_ID.put(534, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(535, 5);
		MONSTER_BY_TASK_ID.put(535, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(536, 15);
		MONSTER_BY_TASK_ID.put(536, "Osprey");
		QUANTITY_BY_TASK_ID.put(537, 20);
		MONSTER_BY_TASK_ID.put(537, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(538, 20);
		MONSTER_BY_TASK_ID.put(538, "Bull shark");
		QUANTITY_BY_TASK_ID.put(539, 25);
		MONSTER_BY_TASK_ID.put(539, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(540, 5);
		MONSTER_BY_TASK_ID.put(540, "Tern");
		QUANTITY_BY_TASK_ID.put(541, 5);
		MONSTER_BY_TASK_ID.put(541, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(542, 5);
		MONSTER_BY_TASK_ID.put(542, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(543, 20);
		MONSTER_BY_TASK_ID.put(543, "Stingray");
		QUANTITY_BY_TASK_ID.put(544, 20);
		MONSTER_BY_TASK_ID.put(544, "Osprey");
		QUANTITY_BY_TASK_ID.put(545, 25);
		MONSTER_BY_TASK_ID.put(545, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(546, 30);
		MONSTER_BY_TASK_ID.put(546, "Great white shark");
		QUANTITY_BY_TASK_ID.put(547, 5);
		MONSTER_BY_TASK_ID.put(547, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(548, 5);
		MONSTER_BY_TASK_ID.put(548, "Spined kraken");
		QUANTITY_BY_TASK_ID.put(549, 5);
		MONSTER_BY_TASK_ID.put(549, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(550, 15);
		MONSTER_BY_TASK_ID.put(550, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(551, 15);
		MONSTER_BY_TASK_ID.put(551, "Osprey");
		QUANTITY_BY_TASK_ID.put(552, 20);
		MONSTER_BY_TASK_ID.put(552, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(553, 25);
		MONSTER_BY_TASK_ID.put(553, "Great white shark");
		QUANTITY_BY_TASK_ID.put(554, 5);
		MONSTER_BY_TASK_ID.put(554, "Tern");
		QUANTITY_BY_TASK_ID.put(555, 5);
		MONSTER_BY_TASK_ID.put(555, "Orca");
		QUANTITY_BY_TASK_ID.put(556, 5);
		MONSTER_BY_TASK_ID.put(556, "Albatross");
		QUANTITY_BY_TASK_ID.put(557, 20);
		MONSTER_BY_TASK_ID.put(557, "Frigatebird");
		QUANTITY_BY_TASK_ID.put(558, 25);
		MONSTER_BY_TASK_ID.put(558, "Eagle ray");
		QUANTITY_BY_TASK_ID.put(559, 25);
		MONSTER_BY_TASK_ID.put(559, "Spined kraken");
		QUANTITY_BY_TASK_ID.put(560, 20);
		MONSTER_BY_TASK_ID.put(560, "Osprey");
		QUANTITY_BY_TASK_ID.put(561, 5);
		MONSTER_BY_TASK_ID.put(561, "Stingray");
		QUANTITY_BY_TASK_ID.put(562, 5);
		MONSTER_BY_TASK_ID.put(562, "Tiger shark");
		QUANTITY_BY_TASK_ID.put(563, 5);
		MONSTER_BY_TASK_ID.put(563, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(564, 30);
		MONSTER_BY_TASK_ID.put(564, "Butterfly ray");
		QUANTITY_BY_TASK_ID.put(565, 30);
		MONSTER_BY_TASK_ID.put(565, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(566, 25);
		MONSTER_BY_TASK_ID.put(566, "Bull shark");
		QUANTITY_BY_TASK_ID.put(567, 30);
		MONSTER_BY_TASK_ID.put(567, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(568, 5);
		MONSTER_BY_TASK_ID.put(568, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(569, 5);
		MONSTER_BY_TASK_ID.put(569, "Great white shark");
		QUANTITY_BY_TASK_ID.put(570, 5);
		MONSTER_BY_TASK_ID.put(570, "Manta ray (monster)");
		QUANTITY_BY_TASK_ID.put(571, 30);
		MONSTER_BY_TASK_ID.put(571, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(572, 30);
		MONSTER_BY_TASK_ID.put(572, "Pygmy kraken");
		QUANTITY_BY_TASK_ID.put(573, 30);
		MONSTER_BY_TASK_ID.put(573, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(574, 30);
		MONSTER_BY_TASK_ID.put(574, "Osprey");
		QUANTITY_BY_TASK_ID.put(575, 5);
		MONSTER_BY_TASK_ID.put(575, "Great white shark");
		QUANTITY_BY_TASK_ID.put(576, 5);
		MONSTER_BY_TASK_ID.put(576, "Manta ray (monster)");
		QUANTITY_BY_TASK_ID.put(577, 5);
		MONSTER_BY_TASK_ID.put(577, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(578, 25);
		MONSTER_BY_TASK_ID.put(578, "Albatross");
		QUANTITY_BY_TASK_ID.put(579, 20);
		MONSTER_BY_TASK_ID.put(579, "Hammerhead shark");
		QUANTITY_BY_TASK_ID.put(580, 30);
		MONSTER_BY_TASK_ID.put(580, "Narwhal");
		QUANTITY_BY_TASK_ID.put(581, 25);
		MONSTER_BY_TASK_ID.put(581, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(582, 5);
		MONSTER_BY_TASK_ID.put(582, "Orca");
		QUANTITY_BY_TASK_ID.put(583, 5);
		MONSTER_BY_TASK_ID.put(583, "Vampyre kraken");
		QUANTITY_BY_TASK_ID.put(584, 5);
		MONSTER_BY_TASK_ID.put(584, "Spined kraken");
		QUANTITY_BY_TASK_ID.put(585, 30);
		MONSTER_BY_TASK_ID.put(585, "Albatross");
		QUANTITY_BY_TASK_ID.put(586, 30);
		MONSTER_BY_TASK_ID.put(586, "Orca");
		QUANTITY_BY_TASK_ID.put(587, 20);
		MONSTER_BY_TASK_ID.put(587, "Vampyre kraken");
		QUANTITY_BY_TASK_ID.put(588, 30);
		MONSTER_BY_TASK_ID.put(588, "Narwhal");
		QUANTITY_BY_TASK_ID.put(589, 5);
		MONSTER_BY_TASK_ID.put(589, "Spined kraken");
		QUANTITY_BY_TASK_ID.put(590, 5);
		MONSTER_BY_TASK_ID.put(590, "Orca");
		QUANTITY_BY_TASK_ID.put(591, 5);
		MONSTER_BY_TASK_ID.put(591, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(592, 20);
		MONSTER_BY_TASK_ID.put(592, "Armoured kraken");
		QUANTITY_BY_TASK_ID.put(593, 30);
		MONSTER_BY_TASK_ID.put(593, "Vampyre kraken");
		QUANTITY_BY_TASK_ID.put(594, 25);
		MONSTER_BY_TASK_ID.put(594, "Narwhal");
		QUANTITY_BY_TASK_ID.put(595, 30);
		MONSTER_BY_TASK_ID.put(595, "Orca");
		QUANTITY_BY_TASK_ID.put(596, 5);
		MONSTER_BY_TASK_ID.put(596, "Albatross");
		QUANTITY_BY_TASK_ID.put(597, 5);
		MONSTER_BY_TASK_ID.put(597, "Vampyre kraken");
		QUANTITY_BY_TASK_ID.put(598, 5);
		MONSTER_BY_TASK_ID.put(598, "Narwhal");
		QUANTITY_BY_TASK_ID.put(605, 5);
		MONSTER_BY_TASK_ID.put(605, "Veiled kraken");
		QUANTITY_BY_TASK_ID.put(606, 15);
		MONSTER_BY_TASK_ID.put(606, "Veiled kraken");
	}

	private WikiBountyFallback()
	{}

	static int getQuantity(int taskId)
	{
		return QUANTITY_BY_TASK_ID.getOrDefault(taskId, 0);
	}

	static String getMonsterName(int taskId)
	{
		return MONSTER_BY_TASK_ID.get(taskId);
	}
}
